/* XPM */
static char * Redo_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 8 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	s iconGray4	m white	c #949494949494",
"o	s iconColor4	m white	c green",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray7	m black	c #424242424242",
"@	c #0000CDCD0000",
"#	s iconColor1	m black	c black",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"              ........          ",
"            ..XXXXXXXXX..       ",
"           .XXXXXXXXXXoXXX.     ",
"        . .XXXXOOOOOOOo+XXXO    ",
"        ..XXXOO       o@+XXXO   ",
"       .XXXXO         o@@+XXXO  ",
"       .Xoooooooooooooo@@@+XO   ",
"      .XXo@@@@@@@@@@@@@@@@@+    ",
"      .XXo@@@@@@@@@@@@@@@@@@+   ",
"     .XXOo@@@@@@@@@@@@@@@@@+    ",
"     .OO o+++++++++++++@@@+     ",
"     O                o@@+      ",
"                      o@+       ",
"                      o+        ",
"                      o         ",
"                                ",
"                                ",
"                                ",
"                                ",
"        ###        #            ",
"        #  #  ##   #  #         ",
"        ###  # # # # # #        ",
"        #  # #   # # # #        ",
"        #  #  ##  ##  #         ",
"                                "};
