/* XPM */
static char * UndoU_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 5 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray4	m white	c #949494949494",
"O	s iconColor1	m black	c black",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"              ........          ",
"            ..XXXXXXXXX..       ",
"           .XXXXXXXXXXXXXX.     ",
"        . .XXXXooooooXXXXXXo    ",
"        .oXXXoo      ooXXXXXo   ",
"       .XXXXo          oXXXXXo  ",
"       .XXXo            .XXXo   ",
"      .XXXXXo            .Xo    ",
"      .XXXoo              .     ",
"     .XXoo                      ",
"     .oo                        ",
"     o                          ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"        O  O       O            ",
"        O  O OOo  oO oOo        ",
"        O  O O O O O O O        ",
"        O  O O O O O O O        ",
"        oOOo O O  OO oOo        ",
"                                "};
