/* XPM */
static char * RedoU_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"34 42 3 1",
/* colors */
" 	s none		m none	c none",
".	s iconGrey1	m white	c grey87",
"X	s iconGrey6	m black	c grey39",
/* pixels */
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"            ........              ",
"           .........X             ",
"          ..........X             ",
"         ....XXXXXXXX             ",
"         ...XX                    ",
"         ...X                     ",
"         ...X        .            ",
"         ...X        ..           ",
"         ....        ...          ",
"         X...............         ",
"          X...............        ",
"           X.............X        ",
"            XXXXXXXXX...X         ",
"                     ..X          ",
"                     .X           ",
"                     X            ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"   XXXXX              X           ",
"   X    X             X           ",
"   X    X   XXX    XX X   XXX     ",
"   X    X  X   X  X  XX  X   X    ",
"   XXXXX   X   X  X   X  X   X    ",
"   X   X   XXXXX  X   X  X   X    ",
"   X    X  X      X   X  X   X    ",
"   X    X  X   X  X  XX  X   X    ",
"   X    X   XXX    XX X   XXX     ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  "};
