/* XPM */
static char * Replay_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"34 42 3 1",
/* colors */
" 	s none		m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor1	m black	c black",
/* pixels */
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"           .                      ",
"           ...                    ",
"           .....                  ",
"           .......                ",
"           .........              ",
"           ...........            ",
"           .............          ",
"           ...............X       ",
"           .............XX        ",
"           ...........XX          ",
"           .........XX            ",
"           .......XX              ",
"           .....XX                ",
"           ...XX                  ",
"           .XX                    ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
" XXXXX              X             ",
" X    X             X             ",
" X    X  XXX  X XX  X  XXX  X   X ",
" X    X X   X XX  X X X   X X   X ",
" XXXXX  X   X X   X X     X X   X ",
" X   X  XXXXX X   X X  XXXX X  X  ",
" X    X X     X   X X X   X  X X  ",
" X    X X   X XX  X X X   X  X X  ",
" X    X  XXX  X XX  X  XXX X  X   ",
"              X               X   ",
"              X              X    ",
"              X             X     ",
"                                  ",
"                                  "};
