/* XPM */
static char * Restart_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"34 42 3 1",
/* colors */
" 	s none		m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor1	m black	c black",
/* pixels */
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"           ..         .           ",
"           ..X       ..X          ",
"           ..X      ...X          ",
"           ..X     ....X          ",
"           ..X    .....X          ",
"           ..X   ......X          ",
"           ..X  .......X          ",
"           ..X ........X          ",
"           ..X  .......X          ",
"           ..X   ......X          ",
"           ..X    .....X          ",
"           ..X     ....X          ",
"           ..X      ...X          ",
"           ..X       ..X          ",
"           ..X        .X          ",
"            XX         X          ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
" XXXX            X            X   ",
" X   X           X            X   ",
" X   X  XX   XX XXX  XX   X XXXX  ",
" X   X X  X X  X X  X  X  XX  X   ",
" XXXX  X  X X    X     X  X   X   ",
" X  X  XXXX  XX  X   XXX  X   X   ",
" X   X X       X X  X  X  X   X   ",
" X   X X  X X  X X  X  X  X   X   ",
" X   X  XX   XX  XX  XX X X   XX  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  "};
