/* XPM */
static char * ToStack_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"34 42 5 1",
/* colors */
" 	s none		m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor3	m black	c red",
"o	s iconColor1	m black	c black",
"O	s iconGrey2	m white	c grey74",
/* pixels */
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"             .........            ",
"            ..X.....X..           ",
"            .XXX...XXX.o          ",
"            ..X.....X..o          ",
"            ...........o          ",
"            ...........o          ",
"            ...........o          ",
"            .....X.....o          ",
"            ....XXX....o          ",
"         .. .....X.....o          ",
"        ....OO.........o          ",
"        .XX...OO.......o          ",
"       ..XX.....OO.....o          ",
"       ...........O.X..o          ",
"      .........XX.OXXX.o          ",
"      .XX......XX.o.X..o          ",
"     ..XX.........o...o           ",
"     ............ooooo            ",
"     ........XX..o                ",
"     XX......XX.o                 ",
"     XX.........o                 ",
"     ..........o                  ",
"                                  ",
"                                  ",
"  o         ooo  o          o     ",
"  o        o   o o          o     ",
" ooo  oo   o    ooo oo   oo o  o  ",
"  o  o  o  o     o o  o o   o o   ",
"  o  o  o   ooo  o    o o   oo    ",
"  o  o  o      o o  ooo o   oo    ",
"  o  o  o  o   o o o  o o   o o   ",
"  o  o  o  o   o o o  o o  oo  o  ",
"  oo  oo    ooo  oo oo o oo o   o ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  "};
