/* XPM */
static char * UndoU_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"34 42 3 1",
/* colors */
" 	s none		m none	c none",
".	s iconGrey1	m white	c grey87",
"X	s iconGrey6	m black	c grey39",
/* pixels */
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"               .                  ",
"              ..X                 ",
"             ...X                 ",
"            ..........            ",
"           ............           ",
"            ............          ",
"             ...XXXXX....         ",
"              ..X    X...X        ",
"               .X     ...X        ",
"                X     ...X        ",
"                      ...X        ",
"                     ....X        ",
"         ...............X         ",
"         ..............X          ",
"         .............X           ",
"          XXXXXXXXXXXX            ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"   X    X             X           ",
"   X    X             X           ",
"   X    X  X XX    XX X   XXX     ",
"   X    X  XX  X  X  XX  X   X    ",
"   X    X  X   X  X   X  X   X    ",
"   X    X  X   X  X   X  X   X    ",
"   X    X  X   X  X   X  X   X    ",
"   X    X  X   X  X  XX  X   X    ",
"    XXXX   X   X   XX X   XXX     ",
"                                  ",
"                                  ",
"                                  ",
"                                  ",
"                                  "};
