/* XPM */
static char * ToStack_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 5 1 -1 -1",
/* colors */
" 	s iconColor5	m black	c blue",
".	s iconColor2	m white	c white",
"X	s iconColor3	m black	c red",
"o	s iconColor1	m black	c black",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
/* pixels */
"                        ",
"                        ",
"        .........       ",
"       ..X.....X..      ",
"       .XXX...XXX.o     ",
"       ..X.....X..o     ",
"       ...........o     ",
"       ...........o     ",
"       ...........o     ",
"       .....X.....o     ",
"       ....XXX....o     ",
"    .. .....X.....o     ",
"   ....OO.........o     ",
"   .XX...OO.......o     ",
"  ..XX.....OO.....o     ",
"  ...........O.X..o     ",
" .........XX.OXXX.o     ",
" .XX......XX.o.X..o     ",
"..XX.........o...o      ",
"............ooooo       ",
"........XX..o           ",
"XX......XX.o            ",
"XX.........o            ",
"..........o             "};
