/* XPM */
static char * Hint_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"40 42 20 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	c #A699BEFBA699",
"o	c #F7DEF7DEEFBE",
"O	c #EFBEF3CEEFBE",
"+	c #E79DEBADE79D",
"@	c #CF3CDB6CCF3C",
"#	c #F7DEF7DEF7DE",
"$	c #D75CDF7DD75C",
"%	c #C71BD75CC71B",
"&	c #AEBAC30BAEBA",
"*	c #BEFBCF3CBEFB",
"=	c #28A228A228A2",
"-	c #E79DEFBEE79D",
";	c #20812CB21861",
":	c #61858A285965",
"?	c #8E38AEBA8617",
">	c #9658B6DA9658",
",	c #BEFBCF3CB6DA",
"<	c #8E38AEBA8E38",
/* pixels */
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                 .....                  ",
"                .XoO+@.                 ",
"               .@#o+++$.                ",
"              .%o&...*+&=               ",
"               .-;   .++.               ",
"               @.    .+&.               ",
"                    .++:.               ",
"                   .++?.                ",
"                  .++?.                 ",
"                 .>+?.                  ",
"                 .+>.                   ",
"                 ....                   ",
"                                        ",
"                  ..                    ",
"                 .+,.                   ",
"                 .,<.                   ",
"                  ..                    ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"          .     .  .         .          ",
"          .     .            .          ",
"          .     .  .  . ..  ...         ",
"          .     .  .  ..  .  .          ",
"          .......  .  .   .  .          ",
"          .     .  .  .   .  .          ",
"          .     .  .  .   .  .          ",
"          .     .  .  .   .  .          ",
"          .     .  .  .   .  ..         ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        "};
