/* XPM */
static char * ReplayU_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"40 42 3 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray1	m white	c #dededededede",
/* pixels */
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                       .                ",
"                       ..               ",
"           X   X X X X .X.              ",
"             X   X X X .XX.             ",
"               X   X X .XXX.            ",
"             X   X   X .XXXX.           ",
"               X   X   .XXXXX.          ",
"                 X   X .XXXX.           ",
"                   X   .XXX.            ",
"                     X .XX.             ",
"                       .X.              ",
"                       ..               ",
"                       .                ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"    .....              .                ",
"    .    .             .                ",
"    .    .  ...  . ..  .  ...  .   .    ",
"    .    . .   . ..  . . .   . .   .    ",
"    .....  .   . .   . .     . .   .    ",
"    .   .  ..... .   . .  .... .  .     ",
"    .    . .     .   . . .   .  . .     ",
"    .    . .   . ..  . . .   .  . .     ",
"    .    .  ...  . ..  .  ... .  .      ",
"                 .               .      ",
"                 .              .       ",
"                 .             .        ",
"                                        ",
"                                        "};
