/* XPM */
static char * ToStack_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"40 42 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	c #E79DE38DCF3C",
"o	s iconGray4	m white	c #949494949494",
"O	c #D75CD75CC71B",
"+	c #EFBEEBADD75C",
"@	c #EFBEEFBED75C",
"#	c #CF3CCF3CB6DA",
"$	c #E79DE79DCF3C",
"%	c #F7DEF3CED75C",
"&	c #DF7DDF7DCF3C",
"*	c #F7DEF3CEDF7D",
"=	c #DF7DDF7DC71B",
"-	c #DF7DDB6CC71B",
";	c #D75CD75CBEFB",
":	c #D75CD34CBEFB",
/* pixels */
"                                        ",
"                                        ",
"                                        ",
"                 ...........            ",
"                .XXXXXXXXXXX.           ",
"                .X.XXXXXXX.X.o          ",
"                .XXXXXXXXXXX.o          ",
"              ...OXXXX.XXXXX.o          ",
"             .+@..#OX.o.XXXX.o          ",
"             .++@@..#O.XXXXX.o          ",
"            .$$.+@@%..#OXXXX.o          ",
"            .X$$++@@%%..#XXX.o          ",
"           .&XX$$++@@%%*.OXX.o          ",
"           .&&XX$$++@.%%.OXX.o          ",
"          .==&&XX$$++@@.#XXX.o          ",
"          .-==&o..$$++@.OXXX.o          ",
"         .O--==&..X$$+.#XXXX.o          ",
"         .OO--=.&oXX$$.OXXXX.o          ",
"        .;;OO--==&&XX.#XXX.X.o          ",
"        .:;;OO--==&&X.OXXXXX.o          ",
"       .#:.;;OO--==&........oo          ",
"       .##::;;OO--==.oooooooo           ",
"        ..#::;;OO--.                    ",
"          ..::;;.O-.                    ",
"            ..:;;O.                     ",
"              ..;;.                     ",
"                ..                      ",
"                                        ",
"   .          ...   .             .     ",
"   .         .   .  .             .     ",
"  ...  ...   .     ...  ..    ..  .  .  ",
"   .  .   .   .     .  .  .  .  . . .   ",
"   .  .   .    ..   .     .  .    ..    ",
"   .  .   .      .  .   ...  .    ..    ",
"   .  .   .  .   .  .  .  .  .    . .   ",
"   .  .   .  .   .  .  .  .  .  . .  .  ",
"   ..  ...    ...   ..  .. .  ..  .   . ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        "};
