/* XPM */
static char * UndoU_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"40 42 3 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray1	m white	c #dededededede",
/* pixels */
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                 .                      ",
"                ..                      ",
"               .X....                   ",
"              .XXXXXX..                 ",
"               .X....XX.                ",
"                ..   .X.                ",
"                 .    .X.               ",
"                       ..               ",
"                       ..               ",
"                       .                ",
"                      .                 ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"       .    .             .             ",
"       .    .             .             ",
"       .    .  . ..    .. .   ...       ",
"       .    .  ..  .  .  ..  .   .      ",
"       .    .  .   .  .   .  .   .      ",
"       .    .  .   .  .   .  .   .      ",
"       .    .  .   .  .   .  .   .      ",
"       .    .  .   .  .  ..  .   .      ",
"        ....   .   .   .. .   ...       ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        "};
